# Generated by Django 4.2.7 on 2023-11-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Матеріали',
            fields=[
                ('код_матеріалу', models.AutoField(primary_key=True, serialize=False)),
                ('назва_матеріалу', models.CharField(max_length=255)),
                ('ціна', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Постачальники',
            fields=[
                ('код_постачальника', models.AutoField(primary_key=True, serialize=False)),
                ('назва_компанії_постачальника', models.CharField(max_length=255)),
                ('контактна_особа', models.CharField(max_length=255)),
                ('телефон', models.CharField(max_length=20)),
                ('розрахунковий_рахунок', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Поставки',
            fields=[
                ('номер_поставки', models.AutoField(primary_key=True, serialize=False)),
                ('дата_поставки', models.DateField()),
                ('кількість_днів', models.PositiveIntegerField()),
                ('кількість_матеріалів', models.PositiveIntegerField()),
                ('код_матеріалу', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.матеріали')),
                ('код_постачальника', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.постачальники')),
            ],
        ),
    ]
